import { Company, Student, PlacementDrive, Application, Interview, Notification, PlacementAnalytics } from './types';

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    website: 'https://techcorp.com',
    hrContact: 'Sarah Johnson',
    hrEmail: 'hr@techcorp.com',
    industry: 'Information Technology',
    location: 'Bangalore, India',
    description: 'Leading software development company specializing in enterprise solutions.',
  },
  {
    id: '2',
    name: 'DataWave Analytics',
    website: 'https://datawave.io',
    hrContact: 'Michael Chen',
    hrEmail: 'careers@datawave.io',
    industry: 'Data Science & AI',
    location: 'Hyderabad, India',
    description: 'AI-powered analytics platform for business intelligence.',
  },
  {
    id: '3',
    name: 'CloudNine Systems',
    website: 'https://cloudnine.com',
    hrContact: 'Priya Sharma',
    hrEmail: 'recruit@cloudnine.com',
    industry: 'Cloud Computing',
    location: 'Pune, India',
    description: 'Cloud infrastructure and DevOps solutions provider.',
  },
  {
    id: '4',
    name: 'FinEdge Technologies',
    website: 'https://finedge.com',
    hrContact: 'Rajesh Kumar',
    hrEmail: 'hr@finedge.com',
    industry: 'Fintech',
    location: 'Mumbai, India',
    description: 'Revolutionary fintech solutions for modern banking.',
  },
  {
    id: '5',
    name: 'GreenTech Innovations',
    website: 'https://greentech.co',
    hrContact: 'Emma Williams',
    hrEmail: 'jobs@greentech.co',
    industry: 'Clean Technology',
    location: 'Chennai, India',
    description: 'Sustainable technology solutions for a greener future.',
  },
];

// Mock Students
export const mockStudents: Student[] = [
  {
    id: '1',
    userId: 'u1',
    name: 'Arjun Patel',
    email: 'arjun.patel@college.edu',
    branch: 'Computer Science',
    cgpa: 8.5,
    skills: ['JavaScript', 'React', 'Node.js', 'Python'],
    resumeUrl: '/resumes/arjun-patel.pdf',
    certifications: ['AWS Certified', 'React Developer'],
    graduationYear: 2024,
    backlogs: 0,
    github: 'https://github.com/arjunpatel',
    linkedin: 'https://linkedin.com/in/arjunpatel',
    phone: '+91 9876543210',
    placementStatus: 'not-placed',
  },
  {
    id: '2',
    userId: 'u2',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@college.edu',
    branch: 'Information Technology',
    cgpa: 9.1,
    skills: ['Java', 'Spring Boot', 'MySQL', 'Docker'],
    resumeUrl: '/resumes/sneha-reddy.pdf',
    certifications: ['Oracle Java Certified', 'Docker Certified'],
    graduationYear: 2024,
    backlogs: 0,
    github: 'https://github.com/snehareddy',
    linkedin: 'https://linkedin.com/in/snehareddy',
    phone: '+91 9876543211',
    placementStatus: 'placed',
  },
  {
    id: '3',
    userId: 'u3',
    name: 'Rahul Verma',
    email: 'rahul.verma@college.edu',
    branch: 'Electronics',
    cgpa: 7.8,
    skills: ['C++', 'Embedded Systems', 'IoT', 'VHDL'],
    resumeUrl: '/resumes/rahul-verma.pdf',
    certifications: ['Embedded Systems Pro'],
    graduationYear: 2024,
    backlogs: 1,
    github: 'https://github.com/rahulverma',
    linkedin: 'https://linkedin.com/in/rahulverma',
    phone: '+91 9876543212',
    placementStatus: 'not-placed',
  },
  {
    id: '4',
    userId: 'u4',
    name: 'Priya Sharma',
    email: 'priya.sharma@college.edu',
    branch: 'Computer Science',
    cgpa: 8.9,
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'Data Analysis'],
    resumeUrl: '/resumes/priya-sharma.pdf',
    certifications: ['Google ML Certified', 'TensorFlow Developer'],
    graduationYear: 2024,
    backlogs: 0,
    github: 'https://github.com/priyasharma',
    linkedin: 'https://linkedin.com/in/priyasharma',
    phone: '+91 9876543213',
    placementStatus: 'not-placed',
  },
  {
    id: '5',
    userId: 'u5',
    name: 'Vikram Singh',
    email: 'vikram.singh@college.edu',
    branch: 'Mechanical',
    cgpa: 8.2,
    skills: ['AutoCAD', 'SolidWorks', 'MATLAB', 'Python'],
    resumeUrl: '/resumes/vikram-singh.pdf',
    certifications: ['SolidWorks Certified'],
    graduationYear: 2024,
    backlogs: 0,
    github: 'https://github.com/vikramsingh',
    linkedin: 'https://linkedin.com/in/vikramsingh',
    phone: '+91 9876543214',
    placementStatus: 'placed',
  },
];

// Mock Placement Drives
export const mockDrives: PlacementDrive[] = [
  {
    id: '1',
    companyId: '1',
    company: mockCompanies[0],
    role: 'Software Development Engineer',
    package: '12 LPA',
    type: 'full-time',
    lastDate: '2024-03-15',
    interviewDate: '2024-03-20',
    eligibility: {
      minCgpa: 7.5,
      branches: ['Computer Science', 'Information Technology'],
      maxBacklogs: 0,
      graduationYear: 2024,
      skills: ['JavaScript', 'React'],
    },
    description: 'Join our team as a Software Development Engineer and work on cutting-edge enterprise solutions.',
    status: 'active',
    applicantsCount: 45,
  },
  {
    id: '2',
    companyId: '2',
    company: mockCompanies[1],
    role: 'Data Scientist',
    package: '15 LPA',
    type: 'full-time',
    lastDate: '2024-03-18',
    interviewDate: '2024-03-25',
    eligibility: {
      minCgpa: 8.0,
      branches: ['Computer Science', 'Information Technology', 'Mathematics'],
      maxBacklogs: 0,
      graduationYear: 2024,
      skills: ['Python', 'Machine Learning'],
    },
    description: 'Work with our AI team to develop next-generation analytics solutions.',
    status: 'active',
    applicantsCount: 32,
  },
  {
    id: '3',
    companyId: '3',
    company: mockCompanies[2],
    role: 'Cloud Engineer Intern',
    package: '40K/month',
    type: 'internship',
    lastDate: '2024-03-10',
    interviewDate: '2024-03-15',
    eligibility: {
      minCgpa: 7.0,
      branches: ['Computer Science', 'Information Technology'],
      maxBacklogs: 1,
      graduationYear: 2025,
      skills: ['AWS', 'Docker'],
    },
    description: '6-month internship opportunity in cloud infrastructure management.',
    status: 'active',
    applicantsCount: 58,
  },
  {
    id: '4',
    companyId: '4',
    company: mockCompanies[3],
    role: 'Backend Developer',
    package: '10 LPA',
    type: 'full-time',
    lastDate: '2024-03-05',
    interviewDate: '2024-03-12',
    eligibility: {
      minCgpa: 7.5,
      branches: ['Computer Science', 'Information Technology'],
      maxBacklogs: 0,
      graduationYear: 2024,
      skills: ['Java', 'Spring Boot'],
    },
    description: 'Build robust backend systems for our fintech platform.',
    status: 'closed',
    applicantsCount: 67,
  },
  {
    id: '5',
    companyId: '5',
    company: mockCompanies[4],
    role: 'Product Design Intern',
    package: '35K/month',
    type: 'internship',
    lastDate: '2024-04-01',
    interviewDate: '2024-04-10',
    eligibility: {
      minCgpa: 7.0,
      branches: ['Computer Science', 'Design'],
      maxBacklogs: 1,
      graduationYear: 2025,
    },
    description: 'Join our design team and create sustainable product solutions.',
    status: 'upcoming',
    applicantsCount: 0,
  },
];

// Mock Applications
export const mockApplications: Application[] = [
  {
    id: '1',
    studentId: '1',
    student: mockStudents[0],
    driveId: '1',
    drive: mockDrives[0],
    status: 'shortlisted',
    appliedAt: '2024-02-28',
  },
  {
    id: '2',
    studentId: '1',
    student: mockStudents[0],
    driveId: '2',
    drive: mockDrives[1],
    status: 'applied',
    appliedAt: '2024-03-01',
  },
  {
    id: '3',
    studentId: '2',
    student: mockStudents[1],
    driveId: '1',
    drive: mockDrives[0],
    status: 'selected',
    appliedAt: '2024-02-25',
  },
  {
    id: '4',
    studentId: '3',
    student: mockStudents[2],
    driveId: '3',
    drive: mockDrives[2],
    status: 'interview-scheduled',
    appliedAt: '2024-03-02',
  },
  {
    id: '5',
    studentId: '4',
    student: mockStudents[3],
    driveId: '2',
    drive: mockDrives[1],
    status: 'shortlisted',
    appliedAt: '2024-03-01',
  },
];

// Mock Interviews
export const mockInterviews: Interview[] = [
  {
    id: '1',
    applicationId: '1',
    application: mockApplications[0],
    round: 'technical',
    roundNumber: 1,
    date: '2024-03-20',
    time: '10:00 AM',
    link: 'https://meet.google.com/abc-defg-hij',
    mode: 'online',
    duration: 45,
    instructions: 'Please join 5 minutes early. Keep your resume and ID card ready. Ensure stable internet connection.',
    status: 'scheduled',
    result: 'pending',
  },
  {
    id: '2',
    applicationId: '4',
    application: mockApplications[3],
    round: 'aptitude',
    roundNumber: 1,
    date: '2024-03-15',
    time: '2:00 PM',
    venue: 'Seminar Hall A',
    mode: 'offline',
    duration: 60,
    instructions: 'Bring your college ID and admit card. Calculator is allowed.',
    status: 'scheduled',
    result: 'pending',
  },
  {
    id: '3',
    applicationId: '5',
    application: mockApplications[4],
    round: 'technical',
    roundNumber: 1,
    date: '2024-03-25',
    time: '11:00 AM',
    link: 'https://meet.google.com/xyz-uvwx-rst',
    mode: 'online',
    duration: 45,
    instructions: 'Focus on Data Structures and Machine Learning concepts.',
    status: 'scheduled',
    result: 'pending',
  },
  {
    id: '4',
    applicationId: '1',
    application: mockApplications[0],
    round: 'aptitude',
    roundNumber: 1,
    date: '2024-02-15',
    time: '9:00 AM',
    venue: 'Main Auditorium',
    mode: 'offline',
    duration: 90,
    feedback: 'Good performance in logical reasoning and quantitative aptitude.',
    status: 'completed',
    result: 'passed',
  },
  {
    id: '5',
    applicationId: '1',
    application: mockApplications[0],
    round: 'hr',
    roundNumber: 2,
    date: '2024-03-22',
    time: '3:00 PM',
    link: 'https://meet.google.com/hr-round-link',
    mode: 'online',
    duration: 30,
    instructions: 'Be prepared to discuss your projects and career goals.',
    status: 'scheduled',
    result: 'pending',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: 'u1',
    title: 'New Placement Drive',
    message: 'TechCorp Solutions has posted a new placement drive for Software Development Engineer.',
    type: 'drive',
    read: false,
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    userId: 'u1',
    title: 'Application Shortlisted',
    message: 'Your application for TechCorp Solutions - SDE has been shortlisted!',
    type: 'application',
    read: false,
    createdAt: '2024-03-02T14:30:00Z',
  },
  {
    id: '3',
    userId: 'u1',
    title: 'Interview Scheduled',
    message: 'Your technical interview is scheduled for March 20, 2024 at 10:00 AM.',
    type: 'interview',
    read: true,
    createdAt: '2024-03-03T09:00:00Z',
  },
  {
    id: '4',
    userId: 'u1',
    title: 'New Drive Alert',
    message: 'DataWave Analytics is hiring Data Scientists with 15 LPA package!',
    type: 'drive',
    read: true,
    createdAt: '2024-03-01T11:00:00Z',
  },
];

// Mock Analytics
export const mockAnalytics: PlacementAnalytics = {
  totalStudents: 450,
  registeredStudents: 420,
  eligibleStudents: 380,
  placedStudents: 285,
  placementPercentage: 75,
  highestPackage: '24 LPA',
  averagePackage: '8.5 LPA',
  companiesVisited: 45,
  activeRecruiters: 32,
  internshipCount: 120,
  departmentWisePlacements: [
    { department: 'Computer Science', placed: 120, total: 150 },
    { department: 'Information Technology', placed: 85, total: 100 },
    { department: 'Electronics', placed: 45, total: 80 },
    { department: 'Mechanical', placed: 25, total: 70 },
    { department: 'Civil', placed: 10, total: 50 },
  ],
  monthlyPlacements: [
    { month: 'Sep', placements: 15 },
    { month: 'Oct', placements: 35 },
    { month: 'Nov', placements: 55 },
    { month: 'Dec', placements: 70 },
    { month: 'Jan', placements: 60 },
    { month: 'Feb', placements: 50 },
  ],
};

// Current logged-in student (for demo)
export const currentStudent: Student = mockStudents[0];

// Auth state helpers
export const branches = [
  'Computer Science',
  'Information Technology',
  'Electronics',
  'Electrical',
  'Mechanical',
  'Civil',
  'Chemical',
  'Mathematics',
  'Design',
];

export const skillsList = [
  'JavaScript',
  'TypeScript',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Python',
  'Java',
  'C++',
  'Go',
  'Rust',
  'SQL',
  'MongoDB',
  'PostgreSQL',
  'AWS',
  'Azure',
  'GCP',
  'Docker',
  'Kubernetes',
  'Machine Learning',
  'Data Science',
  'TensorFlow',
  'PyTorch',
  'DevOps',
  'CI/CD',
];
